# Generated by Django 3.2.4 on 2021-07-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0002_auto_20210701_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem_post',
            field=models.ImageField(upload_to='post_img', verbose_name='Imagem'),
        ),
    ]
