# Generated by Django 3.2.4 on 2021-07-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='email_comentario',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
